services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: signdb
      POSTGRES_USER: signdb_user
      POSTGRES_PASSWORD: signdb_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    ports:
      - 9000:9000
      - 9001:9001

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  backend:
    build: .
    env_file:
      - ./.env.example
    environment:
      # Override key paths to use repo-level mounts below.
      DATASET_ROOT: /dataset
      MODEL_ROOT: /models/active
      INFERENCE_BACKEND: pytorch
      MODEL_ARTIFACT_PATH: /models/active/torch_vn_all_last_v3/model_best.pth.tar

      # Celery
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

      DATABASE_URL: postgresql://signdb_user:signdb_pass@postgres:5432/signdb
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: sign-dataset
    volumes:
      - ../dataset:/dataset
      - ../models:/models
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - minio
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file:
      - ./.env.example
    environment:
      DATASET_ROOT: /dataset
      MODEL_ROOT: /models/active
      INFERENCE_BACKEND: pytorch
      MODEL_ARTIFACT_PATH: /models/active/torch_vn_all_last_v3/model_best.pth.tar
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: postgresql://signdb_user:signdb_pass@postgres:5432/signdb
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: sign-dataset
    volumes:
      - ../dataset:/dataset
      - ../models:/models
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  miniodata:
